name: Patch (MariaDB)

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: patch-mariadb-develop-${{ github.event_name }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  # Do not change this as GITHUB_TOKEN is being used by roulette
  contents: read

jobs:
  checkrun:
    name: Plan Migration
    runs-on: ubuntu-latest

    outputs:
      build: ${{ steps.check-build.outputs.build }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Check if build should be run
        id: check-build
        run: |
          python "${GITHUB_WORKSPACE}/.github/helper/roulette.py"
        env:
          TYPE: "server"
          PR_NUMBER: ${{ github.event.number }}
          REPO_NAME: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  migrate:
    name: Migration
    needs: checkrun
    uses: frappe/frappe/.github/workflows/patch-base.yml@develop
    with:
      python-version: '3.10'
      node-version: 20
      fake-success: ${{ needs.checkrun.outputs.build != 'strawberry' }}
